version: '3.8'

services:
  backend:
    image: slawekradzyminski/backend:1.2
    restart: always
    ports:
      - "4001:4001"
    hostname: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: slawekradzyminski/frontend:1.3
    restart: always
    ports:
      - "8081:8081"

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - influxdb

  activemq:
    image: symptoma/activemq:5.15.13
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    hostname: activemq

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    hostname: activemq

  consumer:
    image: slawekradzyminski/consumer:1.2
    restart: always
    ports:
      - "4002:4002"
    hostname: consumer
    extra_hosts:
      - "host.docker.internal:host-gateway"

  influxdb:
    image: influxdb:1.8
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

volumes:
  influxdb-storage: