version: '3.8'

services:
  backend:
    image: slawekradzyminski/backend:1.2
    restart: always
    ports:
      - "4001:4001"
    hostname: backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my-private-ntwk

  frontend:
    image: slawekradzyminski/frontend:1.3
    restart: always
    ports:
      - "8081:8081"
    networks:
      - my-private-ntwk

networks:
  my-private-ntwk:
    driver: bridge
